name: Deploy S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Delete Existing Content in S3 Bucket
        run: |
          aws s3 rm --recursive s3://ayo-ci-bucket-2

      - name: Deploy Website Content to S3 Bucket
        run: |
          aws s3 sync ./public s3://ayo-ci-bucket-2
